<?php

namespace Tests\Unit\Auth;

use Database\Seeders\UsersTableSeeder;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Artisan;
use Tests\TestCase;

class AuthenticationTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        Artisan::call('passport:install');
    }

    public function testUserCanAuthenticateWithValidCredentials()
    {
        // Запуск сида для создания пользователя
        $this->seed(UsersTableSeeder::class);

        // Получение пользователя из базы данных
        $user = \App\Models\User::first();

        // Создание клиента Passport
        $client = \Laravel\Passport\Client::factory()->create([
            'password_client' => true
        ]);

        // Аутентификация пользователя
        $response = $this->post('/oauth/token', [
            'grant_type' => 'password',
            'client_id' => $client->id,
            'client_secret' => $client->secret,
            'username' => $user->email,
            'password' => 'password', // Используйте фактический пароль пользователя
            'scope' => '',
        ]);

        $response->assertStatus(200);
        $this->assertArrayHasKey('access_token', $response->json());
    }
}
